version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/app/deploy

    #배포가 끝나면 deploy.sh를 실행시킴 (우회하는 방법 사용)
hooks:
  AfterInstall:
    - location: execute-deploy.sh
      timeout: 180