spring:
  profiles:
    active: ${PROFILE}

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB


  s3:
    bucket-name: ${AWS_S3_BUCKET_NAME}
    access-key: ${AWS_ACCESS_KEY_ID}
    secret-key: ${AWS_SECRET_ACCESS_KEY}
    region: ${AWS_REGION}

---
spring:
  config:
    activate:
      on-profile: local
  redis:
    host: localhost
    port: 6379
---
spring:
  config:
    activate:
      on-profile: prod
  redis:
    host: localhost
    port: 6379
---
spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${CLIENT_ID}
            redirect-uri: http://localhost:3000
---
jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: 3600000  # 1 hour in milliseconds

logging:
  level:
    org:
      springframework:
        web: DEBUG
