spring:
  profiles:
    active: ${PROFILE}

---
spring:
  config:
    activate:
      on-profile: local
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

---
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
---

logging:
  level:
    org:
      springframework:
        web: DEBUG
