spring:
  profiles:
    active: ${PROFILE}

---
spring:
  config:
    activate:
      on-profile: local

---
spring:
  config:
    activate:
      on-profile: prod
---
spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${CLIENT_ID}
---
logging:
  level:
    org:
      springframework:
        web: DEBUG

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: 3600000  # 1 hour in milliseconds
  refresh-token-expiration: 86400000  # 1 day in milliseconds
