spring:
  profiles:
    active: ${PROFILE}

---
spring:
  config:
    activate:
      on-profile: local
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

---
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
---

logging:
  level:
    org:
      springframework:
        web: DEBUG

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: 3600000  # 1 hour in milliseconds
  refresh-token-expiration: 86400000  # 1 day in milliseconds
