spring:
  profiles:
    active: ${PROFILE}

---
spring:
  config:
    activate:
      on-profile: local
  redis:
    host: localhost
    port: 6379
---
spring:
  config:
    activate:
      on-profile: prod
  redis:
    host: localhost
    port: 6379
---
spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${CLIENT_ID}
            redirect-uri: http://43.202.94.241:8080/auth/kakao/callback
---
jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: 3600000  # 1 hour in milliseconds

logging:
  level:
    org:
      springframework:
        web: DEBUG
